### ISSUE TITLE
915MHz alternative?

### ISSUE THREAD

**Issue by CEOGavin** [ttn-zh/ic880a-gateway#11]
Hi Guys,

The IMST iC880a board only supports 868MHz. Is there any way to have a 915MHz implementation (legal requirements here in Australia)? 

Please help. Thanks

**Comment by gonzalocasas** [comment]
Hi @CEOGavin! IMST is not manufacturing a 915Mhz version, but RisingHF is, and the good news is that this script is compatible with it. RisingHF has even a board to adapt to the RPi directly, the only difference in that case, is that reset pin needs to be changed, but other than that, it should just work.

**Comment by gonzalocasas** [comment]
I'm gonna close this one, but feel free to contact me on gonzalocasas at gmail

**Comment by thayuriko** [comment]
Hi @gonzalocasas, I'm using a RisingHF board with this adaptor board, but didn't quite understand what you meant with 
> [...] the only difference in that case, is that reset pin needs to be changed, but other than that, it should just work.

Where should I change the reset pin?

**Comment by gonzalocasas** [comment]
Hi @thayuriko, if you use RisingHF's adapter board, then the pin that is used to reset the concentrator is not the same as the one used on the IMST adapter boards. So, you need to change one line of the `start.sh` script to the correct pin number. The line is this one: https://github.com/ttn-zh/ic880a-gateway/blob/spi/start.sh#L4

I hope this clarifies the situation!

cheers!

**Comment by vaz83** [comment]
what's the pin number in this situation? i am facing the same problem
