### ISSUE TITLE
power-via-gpio

### ISSUE THREAD

**Issue by OwenBrotherwood** [ttn-zh/ic880a-gateway#16]
Power via gpio

Are there possible safeguards that could be stated ?
Are there possible safeguards on the pcb (tindie) that could be implemented (barral connector)?

https://github.com/ttn-zh/ic880a-gateway/blob/spi/images/power-via-gpio.jpg

I don't want to forget this thought: if already thought thru: please close, otherwise tracker until sure of power.

---

I go and find some pi reference and may add below this line.

http://raspberrypi.stackexchange.com/questions/1617/how-do-i-supply-power-through-the-gpio

**Comment by dbrgn** [comment]
The [Coredump backplane](https://shop.coredump.ch/product/ic880a-lorawan-gateway-backplane/) has protection against voltage spikes and reverse polarity. I used the same parts as on the Raspi 3 (polyfuse and TVS diode). Protection against reverse polarity is done with a P-FET.
