### ISSUE TITLE
time receiving 

### ISSUE THREAD

**Issue by YousseMes** [ttn-zh/ic880a-gateway#22]
Hi !
thank you for your Job !
I have just one probleme why I receive date every minute and not in really time 
thears some configuration for fix that 

![issu](https://cloud.githubusercontent.com/assets/28385566/26589810/49c055c8-4559-11e7-8fc2-b2374b84ffff.JPG)

**Comment by gonzalocasas** [comment]
Hi!
Could you please add a bit of context. I don't even know exactly what that screenshot is.
But in any case, true real time is not something that works well with LoRaWAN, although I assume you don't mean that but more the time it takes for a message to reach your application. Bit without knowing more about your implementation is very hard to say.

And in any case, chances are the issues at hand are not related to the gateway at all, gateways are pretty simple forwarders.

**Comment by gonzalocasas** [comment]
I'm closing this until we get more details from @YousseMes .
