### ISSUE TITLE
install.sh: GATEWAY_EUI_NIC="eth0" no longer applicable for Raspbian/Debian Stretch

### ISSUE THREAD

**Issue by tandersson** [ttn-zh/ic880a-gateway#24]
Due to the introduction of predictable network interface names in Debian/Raspbian Stretch the use of interface name is now changed to include the mac address. A typical example: 
"enxb827eb8d8982".

**Comment by gonzalocasas** [comment]
Despite Stretch having reverted this default, we finally applied the fix for when this feature is enabled.
