### ISSUE TITLE
Gateway not connected

### ISSUE THREAD

**Issue by localdevm** [ttn-zh/ic880a-gateway#27]
Hello, as of last month I successfully connected my gateway to the network.
Since then however, I have not been able to successfully recreate this connection even though nothing has changed in the configuration.

Illustration:
![lorap issue](http://prntscr.com/h8m4gs)

The current gateway I am using is a ic880-gateway using the TTN legacy packet forwarder protocol. My gateway is (succesfully) registered using the documentation in the README.md of this repository.

You can find my remote config [here](https://github.com/ttn-zh/gateway-remote-config/blob/master/B827EBFFFED1428E.json)

**Comment by gonzalocasas** [comment]
Hi @themaawaa , the link to the image doesn't work. Could you please post it again? Thx

**Comment by localdevm** [comment]
@gonzalocasas Hey gonzalo, for some reason marking my gateway as indoor resulted in it using a gateway far away from me resulting in massive packet loss. Resetting the pi and marking it as outdoor has solved the issue.
