### ISSUE TITLE
HOW DID IT WORK, COULD SOMEBODY SHOW ME A DESCRIBE ?

### ISSUE THREAD

**Issue by SuvanCheng** [ttn-zh/ic880a-gateway#35]
something like “Operational flowchart“

**Comment by gonzalocasas** [comment]
@SuvanCheng if you are interested in details, please be more specific about what you want to know. And also try to be polite, all caps is not good netiquette; always remember that people contributing, do it mostly on their free time, so, be considerate of other people's time when asking questions.

The entire thing is open source, so, if you dig just a little bit deeper, you will find some schematics about the structure. This repository is only an install script that sets up the `poly_packet_forwarder` together with its dependencies on a Raspberry Pi using Raspbian. 

You can find some simple schematics of the setup on the corresponding repositories, e.g. https://github.com/TheThingsNetwork/packet_forwarder/tree/legacy/poly_pkt_fwd

If you have more questions, please consider posting a forum topic, not a github issue.
