### ISSUE TITLE
Question: Does this allow fine timestamps?

### ISSUE THREAD

**Issue by 1kastner** [ttn-zh/ic880a-gateway#37]
Hi there,

for TDoA (Time Difference of Arrival) triangulation for geopositioning we need very precise timestamps. Have you tried in your setup whether timestamps can be retrieved in nanoseconds instead of the default microseconds? To know that would be really great! Thanks a lot in advance!

Best wishes!

**Comment by gonzalocasas** [comment]
No, it doesn't. The RPi is not accurate enough and the design of the concentrator itself is not one of those v2 ref designs, so, nope, cannot be done reliably.
