### ISSUE TITLE
How to use it with RAK831 via ft2232h?

### ISSUE THREAD

**Issue by promistrio** [ttn-zh/ic880a-gateway#44]

**Comment by gonzalocasas** [comment]
@promistrio I have no idea. As far as I know, the ft2232h is a USB interface, which would be really not the recommended way to connect it. SPI interface was given priority support and the USB one was deprecated by Semtech several years ago, claiming the speed was not fast enough (iirc).

If you want to try using the `master` branch which still supports usb, you're more than welcome, but for the time being, I will close this issue.
