### ISSUE TITLE
Improvement on antenna

### ISSUE THREAD

**Issue by yerpj** [ttn-zh/ic880a-gateway#5]
Hello guys.
First I would like to say that your job is impressive! I wish I lived in Zurich. We do not have most coverage here in Lausanne and Yverdon, even if I heard that [Octanis](http://octanis.org/) installed a gateway recently near the EPFL.

I am not a RF guy, but I work with some of them.In my opinion it should be of importance to specify in your wiki that the antenna SHOULD be a 1/2wavelength. If 1/4wavelength, the mounting instructions are missing a rock-solid copper-foil ground plane.

Once more, thumbs up for all the work you are doing!

**Comment by gonzalocasas** [comment]
Hi @yerpj! Thanks for the feedback! I added the 1/2 wavelength remark. Is it correct as it is now? I also added a few links to other higher gain antennas from Aliexpress.

**Comment by yerpj** [comment]
Yes that's better! This will avoid confusion. Thank you.
