### ISSUE TITLE
Help: what for settings?

### ISSUE THREAD

**Issue by MakeMagazinDE** [ttn-zh/ic880a-gateway#50]
Why I must fill out the settings like email, lat/long and so on? what is this information used for? I can edit it all on the TTN account.

**Comment by gonzalocasas** [comment]
You certainly can only keep it on the TTN account, this was developed way before the Web UI of TTN would allow you to register gateways and enter that information, so it was needed back then; now it is secondary to the info of the console. Notice however that your gateway works without registering it on the console anyway, so in that sense, you could consider these settings as defaults, and optionally overwritable from the console.
