### ISSUE TITLE
error: pathspec 'legacy' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by 1012207826** [ttn-zh/ic880a-gateway#63]
I meet a issue that"error: pathspec 'legacy' did not match any file(s) known to git.",and I don't now how to solve it.

**Comment by gonzalocasas** [comment]
I would need a lot more information to understand what might be wrong. When exactly do you get this error? Which setup do you have? Anything different from the instructions on the wiki?

**Comment by 1012207826** [comment]
Firstly,Thank you give me replay，and I am very happy.
I want to install loraserver ,and I have downloaded files from github.But I met a promlbe when I was Installing the server。following the pictures.

then I use the commands:pi@rak-gateway:~/ic880a-gateway $ sudo ./install.sh ips

From the above picture ,I chose the install it from local file,so I met the follow problem,and I don't know where I should configure the file of json.
Can you help me? Thank you




------------------ 原始邮件 ------------------
发件人: "Gonzalo Casas"<notifications@github.com>; 
发送时间: 2019年10月4日(星期五) 凌晨0:45
收件人: "ttn-zh/ic880a-gateway"<ic880a-gateway@noreply.github.com>; 
抄送: "深山红叶"<1012207826@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ttn-zh/ic880a-gateway] error: pathspec 'legacy' did not matchany file(s) known to git. (#63)




I would need a lot more information to understand what might be wrong. When exactly do you get this error? Which setup do you have? Anything different from the instructions on the wiki?

**Comment by gonzalocasas** [comment]
`sudo ./install.sh ips` -> that is wrong. The last argument should be `spi` not `ips`.
