### ISSUE TITLE
Not possible to clone ic880a-gateway.git when using Buster

### ISSUE THREAD

**Issue by BerndGaykema** [ttn-zh/ic880a-gateway#64]
Due to a voltage interruption to my RPi the SD card with the gateway software on it crashed.
Time to make a fresh card with the latest Raspbian light software.
I have done this several times without any issue, but it is the first time with BUSTER LIGHT.

I have followed all the steps in the wiki. When I arrived at the clone step I got an error message:

start screen dump:

**ttn@raspberrypi:~ $** git clone https://github.com/ttn-zh/ic880a-gateway.git ~/ic880a-gateway

Cloning into '/home/ttn/ic880a-gateway'...

/usr/lib/git-core/git-remote-https: error while loading shared libraries: er▒: cannot open shared object file: No such file or directory

**ttn@raspberrypi:~ $**

stop screen dump

**Comment by BerndGaykema** [comment]
I give a fresh install of Stretch light a chance and BINGO, it works as before.
My gateway is up and running again. Now I have to find a UPS-solution for my RPi ;-)

**Comment by gonzalocasas** [comment]
👍👍
glad to hear!
