### ISSUE TITLE
ic880a installer with RAK831 concentrator board

### ISSUE THREAD

**Issue by Faizan2253** [ttn-zh/ic880a-gateway#79]
Hi there,
I have RAK831 concentrator board (433 Mhz). I saw many getting started tutorials for this board which uses IC880a installer to  go on.
When I connected the RAK  officials (manufacturer of RAK831) they say ic880a installer is not compatible with RAK831 board. They sent me the link of there own installer to connect my gateway to TTN.
So can you tell me is ic880a really not compatible with RAK831?
Thanks!!!!

**Comment by gonzalocasas** [comment]
Well, if they said it is not, then, I don't know why I should need to add anything to that statement.
