### ISSUE TITLE
Followed Guide but still no connection.

### ISSUE THREAD

**Issue by Mdmilne** [ttn-zh/ic880a-gateway#85]
Hi there, I followed your guide for reating a LoRa Gateway with the Raspberry Pi and ic880a board very closely but when I reach the end my status on TTN is still "disconnected".  I have uploaded the json file to the repository for remote settings and it was accepted but when I run the "sudo ./install.sh spi" on my raspberry pi, the final lines in the command window are:

error: object file .git/objets/d7/5ec001c15f8c600f093eb82e0de9bd6d12549d is empty
fatal: loose object d75ec001c15f8c600f093eb82e0de9bd6d12549d (stored in .git/objets/d7/5ec001c15f8c600f093eb82e0de9bd6d12549d) is corrupt

Could this be the reason for failure?  Are there any more recent settings/changes I should be aware of?
Thank you,
Matthew

**Comment by gonzalocasas** [comment]
That looks weird indeed... I would suggest removing the whole installation folder `/opt/ttn-gateway` and run a clean install again.
