### ISSUE TITLE
Setup in Beaglebone black

### ISSUE THREAD

**Issue by CHMSFlix** [ttn-zh/ic880a-gateway#89]
Hi, 

I am trying to set up the gateway in BBB.  

Already, I have done with Rpi 3. It's working fine. 

Can I follow the same setup commands in beaglebone black? if not can you suggest some of the docs, to follow the setup for ic880a gateway with TTN?

Thanks,

**Comment by gonzalocasas** [comment]
I don't know. I assume for the most part it would work, but the SPI interface might be different. Give it a try and let us know if it did work.
