### ISSUE TITLE
Important power

### ISSUE THREAD

**Issue by dicktonyboy** [ttn-zh/ic880a-gateway#9]
What does this mean exactly?

Plug the iC880a (WARNING: first power plug to the wall socket, then to the gateway DC jack, and ONLY THEN USB to RPi!)

**Comment by gonzalocasas** [comment]
This warning is copied from IMST's datasheet about the iC880A USB version:

![image](https://cloud.githubusercontent.com/assets/933277/19032666/8067c72e-895b-11e6-807b-2435f6d6577b.png)

Page 12 of this document: http://www.wireless-solutions.de/images/stories/downloads/Radio%20Modules/iC880A/iC880A_Datasheet_V0_17.pdf

**Comment by dicktonyboy** [comment]
Thanks for this - I almost knew as I hit the button that it would be resolved.  Horribly ambiguous referring to a **now defunct version**. I see they have this on the current SPI version.  
![psu_connections](https://cloud.githubusercontent.com/assets/4680593/19185076/ecfca930-8c77-11e6-8297-1a300747de5b.png)

http://www.wireless-solutions.de/images/stories/downloads/Radio%20Modules/iC880A/iC880A-SPI_QuickStartGuide.pdf
